# Generated by Django 4.1.7 on 2023-02-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='folder_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
