# Generated by Django 4.1.7 on 2023-03-13 09:46

from django.db import migrations, models
import f2api.models


class Migration(migrations.Migration):

    dependencies = [
        ('f2api', '0002_rename_name_profile_folder_name_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, upload_to=f2api.models.Profile.fileName),
        ),
        migrations.AlterField(
            model_name='profile',
            name='folder_name',
            field=models.CharField(max_length=300),
        ),
    ]
